project:
  type: website

website:
  title: "Calibração de Inóculo Fungico"
  navbar:
    left:
      - href: index.qmd    
      - text: Endrio Webers 
        href: https://endriowebers.github.io/
      - icon: github 
        href: https://github.com/endriowebers

format:
  html:
    theme: 
      - cosmo
      - estilo_ERW.scss


page-footer:
    background: light # or dark
    left:
      - "Copyright 2024, Endrio Webers"
    right:
      - icon: github
        href: https://github.com/endriowebers
