project:
  type: website

website:
  title: "calibrainoculo"
  navbar:
    left:
      - href: index.qmd
        text: Calibração de Inóculo

format:
  html:
    theme: 
      - cosmo
      - estilo_ERW.scss


page-footer:
    background: light # or dark
    left:
      - "Copyright 2024, Endrio Webers"
    right:
      - icon: github
        href: https://github.com/endriowebers
