on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch: {}

name: demo-website

jobs:
  # Job para construir o site
  build: # Renomeado de "demo-website" para "build" por clareza
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Setup pandoc"
        uses: r-lib/actions/setup-pandoc@v2

      - name: "Setup R"
        uses: r-lib/actions/setup-r@v2

      - name: "Setup R dependencies for Quarto's knitr engine"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            shinylive
            knitr
            rmarkdown
            downlit
            xml2
            dplyr
            webr
            bslib 

      - name: "Set up Quarto"
        uses: quarto-dev/quarto-actions/setup@v2

      - name: "Render working directory"
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload Pages artifact
        # Ação atualizada da v2 para v3
        uses: actions/upload-pages-artifact@v3
        with:
          # O caminho do artefato é automaticamente detectado pelo Quarto
          # então não é mais necessário especificá-lo
          path: _site/

  # Job para fazer o deploy
  deploy:
    runs-on: ubuntu-latest
    # Precisa esperar o job de build terminar
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # Ação atualizada da v2 para v4
        uses: actions/deploy-pages@v4